export const destinyActivityModeType = {
    AllPvP: 5,
    Control: 10,
    Clash: 12,
    CrimsonDoubles: 15,
    IronBanner: 19,
    AllMayhem: 25,
    Supremacy: 31,
    PrivateMatchesAll: 32,
    Survival: 37,
    Countdown: 38,
    TrialsOfTheNine: 39,
    TrialsCountdown: 41,
    TrialsSurvival: 42,
    IronBannerControl: 43,
    IronBannerClash: 44,
    IronBannerSupremacy: 45,
    Rumble: 48,
    AllDoubles: 49,
    Doubles: 50,
    PrivateMatchesClash: 51,
    PrivateMatchesControl: 52,
    PrivateMatchesSupremacy: 53,
    PrivateMatchesCountdown: 54,
    PrivateMatchesSurvival: 55,
    PrivateMatchesMayhem: 56,
    PrivateMatchesRumble: 57,
    Showdown: 59,
    Lockdown: 60,
    Scorched: 61,
    ScorchedTeam: 62,
    Breakthrough: 65,
    Salvage: 67,
    IronBannerSalvage: 68,
    PvPCompetitive: 69,
    PvPQuickplay: 70,
    ClashQuickplay: 71,
    ClashCompetitive: 72,
    ControlQuickplay: 73,
    ControlCompetitive: 74,
    Elimination: 80,
    Momentum: 81,
    TrialsOfOsiris: 84
};

export const destinyComponentType = {
    None: 0,
    Profiles: 100,
    Characters: 200
};